python ./main.py --model 0 --lr 0.1 -o sgd -d ./save/0
python ./main.py --model 0 --lr 0.1 -o adam -d ./save/0
python ./main.py --model 0 --lr 0.05 -o sgd -d ./save/0
python ./main.py --model 0 --lr 0.05 -o adam -d ./save/0
python ./main.py --model 0 --lr 0.02 -o sgd -d ./save/0
python ./main.py --model 0 --lr 0.02 -o adam -d ./save/0
python ./main.py --model 0 --lr 0.01 -o sgd -d ./save/0
python ./main.py --model 0 --lr 0.01 -o adam -d ./save/0
python ./main.py --model 0 --lr 0.005 -o sgd -d ./save/0
python ./main.py --model 0 --lr 0.005 -o adam -d ./save/0
python ./main.py --model 0 --lr 0.002 -o sgd -d ./save/0
python ./main.py --model 0 --lr 0.002 -o adam -d ./save/0
python ./main.py --model 0 --lr 0.001 -o sgd -d ./save/0
python ./main.py --model 0 --lr 0.001 -o adam -d ./save/0
python ./main.py --model 0 --lr 0.0005 -o sgd -d ./save/0
python ./main.py --model 0 --lr 0.0005 -o adam -d ./save/0
python ./main.py --model 0 --lr 0.0001 -o sgd -d ./save/0
python ./main.py --model 0 --lr 0.0001 -o adam -d ./save/0
python ./main.py --model 1 --lr 0.1 -o sgd -d ./save/1
python ./main.py --model 1 --lr 0.1 -o adam -d ./save/1
python ./main.py --model 1 --lr 0.05 -o sgd -d ./save/1
python ./main.py --model 1 --lr 0.05 -o adam -d ./save/1
python ./main.py --model 1 --lr 0.02 -o sgd -d ./save/1
python ./main.py --model 1 --lr 0.02 -o adam -d ./save/1
python ./main.py --model 1 --lr 0.01 -o sgd -d ./save/1
python ./main.py --model 1 --lr 0.01 -o adam -d ./save/1
python ./main.py --model 1 --lr 0.005 -o sgd -d ./save/1
python ./main.py --model 1 --lr 0.005 -o adam -d ./save/1
python ./main.py --model 1 --lr 0.002 -o sgd -d ./save/1
python ./main.py --model 1 --lr 0.002 -o adam -d ./save/1
python ./main.py --model 1 --lr 0.001 -o sgd -d ./save/1
python ./main.py --model 1 --lr 0.001 -o adam -d ./save/1
python ./main.py --model 1 --lr 0.0005 -o sgd -d ./save/1
python ./main.py --model 1 --lr 0.0005 -o adam -d ./save/1
python ./main.py --model 1 --lr 0.0001 -o sgd -d ./save/1
python ./main.py --model 1 --lr 0.0001 -o adam -d ./save/1
python ./main.py --model 3 --lr 0.1 -o sgd -d ./save/3
python ./main.py --model 3 --lr 0.1 -o adam -d ./save/3
python ./main.py --model 3 --lr 0.05 -o sgd -d ./save/3
python ./main.py --model 3 --lr 0.05 -o adam -d ./save/3
python ./main.py --model 3 --lr 0.02 -o sgd -d ./save/3
python ./main.py --model 3 --lr 0.02 -o adam -d ./save/3
python ./main.py --model 3 --lr 0.01 -o sgd -d ./save/3
python ./main.py --model 3 --lr 0.01 -o adam -d ./save/3
python ./main.py --model 3 --lr 0.005 -o sgd -d ./save/3
python ./main.py --model 3 --lr 0.005 -o adam -d ./save/3
python ./main.py --model 3 --lr 0.002 -o sgd -d ./save/3
python ./main.py --model 3 --lr 0.002 -o adam -d ./save/3
python ./main.py --model 3 --lr 0.001 -o sgd -d ./save/3
python ./main.py --model 3 --lr 0.001 -o adam -d ./save/3
python ./main.py --model 3 --lr 0.0005 -o sgd -d ./save/3
python ./main.py --model 3 --lr 0.0005 -o adam -d ./save/3
python ./main.py --model 3 --lr 0.0001 -o sgd -d ./save/3
python ./main.py --model 3 --lr 0.0001 -o adam -d ./save/3
python ./main.py --model 4 --lr 0.1 -o sgd -d ./save/4
python ./main.py --model 4 --lr 0.1 -o adam -d ./save/4
python ./main.py --model 4 --lr 0.05 -o sgd -d ./save/4
python ./main.py --model 4 --lr 0.05 -o adam -d ./save/4
python ./main.py --model 4 --lr 0.02 -o sgd -d ./save/4
python ./main.py --model 4 --lr 0.02 -o adam -d ./save/4
python ./main.py --model 4 --lr 0.01 -o sgd -d ./save/4
python ./main.py --model 4 --lr 0.01 -o adam -d ./save/4
python ./main.py --model 4 --lr 0.005 -o sgd -d ./save/4
python ./main.py --model 4 --lr 0.005 -o adam -d ./save/4
python ./main.py --model 4 --lr 0.002 -o sgd -d ./save/4
python ./main.py --model 4 --lr 0.002 -o adam -d ./save/4
python ./main.py --model 4 --lr 0.001 -o sgd -d ./save/4
python ./main.py --model 4 --lr 0.001 -o adam -d ./save/4
python ./main.py --model 4 --lr 0.0005 -o sgd -d ./save/4
python ./main.py --model 4 --lr 0.0005 -o adam -d ./save/4
python ./main.py --model 4 --lr 0.0001 -o sgd -d ./save/4
python ./main.py --model 4 --lr 0.0001 -o adam -d ./save/4
